name: CI Build for Docker with External Action
on: [workflow_dispatch]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        id: SayHello
        uses: fred-gagnon/hello-world-docker-action@v1
        with:
          who-to-greet: '@FredGagnon'

      - name: Print output
        shell: bash
        run: |
          echo "We said hello at '${{ steps.SayHello.outputs.time }}'"
