name: Reuse Workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      who-to-greet: ${{ github.actor }}

  use-output:
    needs: [call-workflow]
    runs-on: ubuntu-latest
    steps:
    - name: Print Output
      id: PrintOutput
      shell: bash
      run: |
        echo "Output was '${{ needs.call-workflow.outputs.current-time }}'"

