name: CacheTest

on: [create, workflow_dispatch]

permissions: 
  issues: write
  contents: read

jobs:
  GenerateArtifact:
    runs-on: windows-latest
    steps:
      - name: Create Artifact
        shell: pwsh
        run: |
          Get-Command -Name zstd | Out-String | Write-Host

          [string]$path = Join-Path -Path '${{ runner.workspace }}' -ChildPath 'Cache/BigFile.txt'
          New-Item -Path $path -ItemType File -Force | Out-Null
          [byte[]]$out = New-Object -TypeName 'byte[]' -ArgumentList (1GB)
          New-Object -TypeName 'Random' | ForEach-Object { $_.NextBytes($out) }
          [IO.File]::WriteAllBytes($path, $out)
          Get-Item -Path $path

      - name: Cache File
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/Cache
          key: MyCache-${{ github.run_id }}
  
  RestoreArtifact:
    runs-on: windows-latest
    needs: GenerateArtifact
    steps:
      - name: Restore Cache
        uses: actions/cache@v4
        with:
          path: ${{ runner.workspace }}/Cache
          key: MyCache-${{ github.run_id }}

      - name: Test Artifact
        shell: pwsh
        run: |
          [string]$path = Join-Path -Path '${{ runner.workspace }}' -ChildPath 'Cache/BigFile.txt' -Resolve
          Get-Item -Path $path
